version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: think_business_registration
    # volumes:
      # - db_data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

# volumes:
#   db_data:
#     driver: local

# networks:
#   default:
#     name: app-network